package dev.pixelied.survival.damage;

public enum DamageFlag {
    BYPASSES_INVULNERABILITY,
    BYPASSES_COOLDOWN,
    BYPASSES_ARMOR,
    BYPASSES_SHIELD,
    BYPASSES_EFFECTS,
    BYPASSES_RESISTANCE,
    BYPASSES_ENCHANTMENTS,
    IS_FIRE,
    BURN_FROM_STEPPING,
    IS_PROJECTILE,
    IS_EXPLOSION,
    IS_FALL,
    IS_DROWNING,
    IS_FREEZING,
    IS_LIGHTNING,
    IS_MACE_SMASH,
    DAMAGES_HELMET
}
