package dev.adrien.crystaloptimizer.execution;

public enum CommitAbortReason {
    MISSING_REQUIRED_EXPLOSIVE,
    TARGET_OUTSIDE_VIABLE_GEOMETRY,
    RESOURCE_RESERVATION_FAILED,
    UNACCEPTABLE_SELF_SURVIVAL,
    RECONCILIATION_INVALIDATED,
    AUTO_TOTEM_EMERGENCY,
    ACTION_DISPATCH_FAILED
}
